// ** Import CSS
import "./globals.css";

// ** Import Components
import Navbar from "@/components/landing-page/navbar/Navbar";
import Footer from "@/components/landing-page/Footer/Footer";

import { Inter, Poppins } from "next/font/google";

const poppins = Poppins({
  weight: "500",
  subsets: ["devanagari"],
});

export const metadata = {
  title: "Geomuda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />

          {children}

        <Footer />
      </body>
    </html>
  );
}
